apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: costbudgets.sre.agent-os.dev
spec:
  group: sre.agent-os.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                agentId:
                  type: string
                budgetUsd:
                  type: number
                windowDays:
                  type: integer
                alertThresholdPercent:
                  type: number
            status:
              type: object
              properties:
                spentUsd:
                  type: number
                remainingUsd:
                  type: number
                lastUpdated:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: costbudgets
    singular: costbudget
    kind: CostBudget
    shortNames:
      - cb
