name: 🐛 Bug Report
description: Report a bug in Agent SRE
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install agent-sre v...
        2. Configure SLO with...
        3. Run...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g. Ubuntu 22.04, macOS 14, Windows 11
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: e.g. 3.10, 3.11, 3.12
    validations:
      required: true

  - type: dropdown
    id: engine
    attributes:
      label: Engine Affected
      description: Which Agent SRE engine is affected?
      multiple: true
      options:
        - SLO Engine
        - Replay Engine
        - Chaos Engine
        - Progressive Delivery
        - Cost Guard
        - Incident Manager
        - Other / Not sure
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots.
