name: ✨ Feature Request
description: Suggest a new feature for Agent SRE
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise summary of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.

  - type: dropdown
    id: engine
    attributes:
      label: Engine Affected
      description: Which Agent SRE engine does this relate to?
      multiple: true
      options:
        - SLO Engine
        - Replay Engine
        - Chaos Engine
        - Progressive Delivery
        - Cost Guard
        - Incident Manager
        - New Engine / Cross-cutting
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references.
